'use client';
import {useRef,useState} from 'react';
import {ArrowDown,ArrowUpRight,Check,ChevronLeft,ChevronRight,Clapperboard,Copy,Download,Film,CodeXml,Mail,MessageCircle,Music2,Sparkles,ZoomIn} from 'lucide-react';
import {MATERIAL_CONTACT,MATERIAL_GALLERIES,type MaterialGallery,type MaterialImage} from '@/lib/editing-materials';
import {Modal} from './modal';

interface Preview {title:string;images:MaterialImage[];index:number;}
function Gallery({gallery,onOpen}:{gallery:MaterialGallery;onOpen:(index:number)=>void}){
  const [index,setIndex]=useState(0);const start=useRef({x:0,y:0});const swiped=useRef(false);
  const current=gallery.images[index];const move=(step:number)=>setIndex(value=>(value+step+gallery.images.length)%gallery.images.length);
  return <div className="material-gallery"><button className="material-image" aria-label={`放大${current.label}`} onPointerDown={event=>{swiped.current=false;start.current={x:event.clientX,y:event.clientY};event.currentTarget.setPointerCapture(event.pointerId);}} onPointerUp={event=>{const x=event.clientX-start.current.x,y=event.clientY-start.current.y;swiped.current=Math.hypot(x,y)>8;if(Math.abs(x)>50&&Math.abs(x)>Math.abs(y))move(x<0?1:-1);}} onPointerCancel={()=>{swiped.current=false;}} onClick={()=>{if(swiped.current){swiped.current=false;return;}onOpen(index);}}><img key={current.src} src={current.src} alt={current.label} loading="lazy" draggable={false}/><span className="material-zoom"><ZoomIn size={13}/>点击看大图</span></button><div className="material-gallery-controls"><button className="icon-button" aria-label={`${gallery.title}上一张`} onClick={()=>move(-1)}><ChevronLeft size={17}/></button><span aria-live="polite">{index+1} / {gallery.images.length}</span><button className="icon-button" aria-label={`${gallery.title}下一张`} onClick={()=>move(1)}><ChevronRight size={17}/></button></div><div className="material-thumbnails" aria-label={`${gallery.title}图集`}>{gallery.images.map((image,i)=><button key={image.src} aria-label={`${gallery.title}第 ${i+1} 张`} aria-pressed={index===i} onClick={()=>setIndex(i)}><img src={image.src} alt="" loading="lazy"/></button>)}</div></div>;
}
export function EditingMaterials({motion}:{motion:boolean}){
  const [preview,setPreview]=useState<Preview|null>(null);const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState('');
  function jump(id:string){document.getElementById(id)?.scrollIntoView({behavior:motion?'smooth':'instant',block:'start'});}
  async function copyWechat(){try{await navigator.clipboard.writeText(MATERIAL_CONTACT.wechat);setCopied(true);setCopyError('');}catch{setCopyError('未能自动复制，请长按上方微信号复制。');}}
  function movePreview(step:number){setPreview(value=>value?{...value,index:(value.index+step+value.images.length)%value.images.length}:null);}
  return <section className="materials-page section-enter">
    <div className="paper materials-hero"><div className="materials-hero-copy"><div className="materials-brand"><img src={MATERIAL_CONTACT.avatar} alt="月海的头像"/><span><strong>YOcean</strong><small>月海的剪辑素材小站</small></span><Clapperboard size={28}/></div><span className="eyebrow">LITTLE EDITS, BIG FEELINGS</span><h2>给剪辑，<br/><span>找一点灵感。</span></h2><p>还在苦于剪辑没素材吗？<br/>把喜欢的舞台与镜头，剪成心里的那段故事。</p><div className="materials-hero-actions"><button className="button primary" onClick={()=>jump('materials-galleries')}><Film size={15}/>翻翻素材 <ArrowDown size={14}/></button><button className="button secondary" onClick={()=>jump('materials-contact')}><MessageCircle size={15}/>联系月海</button></div></div><div className="materials-hero-picture"><img src={MATERIAL_GALLERIES[0].images[0].src} alt="K-pop 舞台素材展示"/><span><Music2 size={16}/>a little inspiration for your next edit</span><i aria-hidden="true">✦</i></div></div>
    <div className="paper material-intro-note"><span className="material-note-icon"><Download size={22}/></span><div><span className="eyebrow">BEFORE YOU START</span><h3>先看一眼这张小纸条</h3><p>素材使用百度网盘获取，需要准备百度网盘。以网盘分享为主，不建 QQ 群或微信群，避免群内素材过期。</p><p>部分素材是 4K 视频，建议先确认你的设备与播放器可以正常打开，再选择需要的素材。</p></div><Sparkles size={24} aria-hidden="true"/></div>
    <div id="materials-galleries" className="material-section-heading"><span className="eyebrow">THE MATERIAL SHELF</span><h3>挑一份喜欢，开始下一次剪辑<span className="heading-dot">.</span></h3><p>翻翻展示图，想看细节时点开大图。</p></div>
    <div className="material-groups">{MATERIAL_GALLERIES.map((gallery,i)=><article className={`paper material-group material-group-${i}`} key={gallery.id}><Gallery gallery={gallery} onOpen={index=>setPreview({title:gallery.title,images:gallery.images,index})}/><div className="material-group-copy"><span className="eyebrow">{gallery.eyebrow}</span><h3>{gallery.title}</h3><div className="material-share"><span><Download size={13}/>{gallery.share}</span></div><p>{gallery.description}</p><ul>{gallery.features.map(feature=><li key={feature}><Check size={13}/>{feature}</li>)}</ul><button className="text-button" onClick={()=>jump('materials-contact')}>想聊聊这一份 <ArrowUpRight size={14}/></button><span className="material-card-flower" aria-hidden="true">{['✧','♫','♡'][i]}</span></div></article>)}</div>
    <div className="materials-contact-grid" id="materials-contact"><article className="paper material-douyin"><span className="eyebrow">MY LITTLE EDITS</span><h3>也来看看我的剪辑吧<span className="heading-dot">.</span></h3><p>素材还在慢慢更新，剪好的心动瞬间留在抖音。</p><button className="douyin-picture" onClick={()=>setPreview({title:'抖音主页',images:[MATERIAL_CONTACT.douyinImage],index:0})} aria-label="预览抖音主页截图"><img src={MATERIAL_CONTACT.douyinImage.src} alt="抖音主页截图" loading="lazy"/><span><ZoomIn size={14}/>查看主页截图</span></button><a className="button secondary" href={MATERIAL_CONTACT.douyin} target="_blank" rel="noopener noreferrer"><Music2 size={15}/>前往抖音主页 <ArrowUpRight size={14}/></a></article><article className="paper material-contact"><span className="eyebrow">SAY HELLO</span><h3>留一句来意，慢慢聊</h3><p>想聊聊素材，或者只是打个招呼，都可以私信抖音或加个微信好友。注明来意，更快通过哦。</p><button className="material-qr" onClick={()=>setPreview({title:'微信好友二维码',images:[MATERIAL_CONTACT.qr],index:0})} aria-label="放大微信好友二维码"><img src={MATERIAL_CONTACT.qr.src} alt="微信好友二维码" loading="lazy"/></button><span className="material-qr-caption">扫一扫，加个好友慢慢聊</span><div className="material-wechat"><MessageCircle size={17}/><strong>{MATERIAL_CONTACT.wechat}</strong><button className="icon-button" onClick={()=>void copyWechat()} aria-label="复制微信号">{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><p className="material-copy-result" role="status">{copyError||(copied?'微信号已复制':'')}</p><div className="material-other-links"><a href={`mailto:${MATERIAL_CONTACT.email}`}><Mail size={14}/>邮箱</a><a href={MATERIAL_CONTACT.github} target="_blank" rel="noopener noreferrer"><CodeXml size={14}/>GitHub <ArrowUpRight size={12}/></a></div></article></div>
    <p className="materials-signoff">♫ &nbsp; 把喜欢的镜头，剪成自己的故事。 &nbsp; ♡</p>
    {preview&&<Modal title={`${preview.title}${preview.images.length>1?` · ${preview.index+1} / ${preview.images.length}`:''}`} onClose={()=>setPreview(null)} wide><div className="material-lightbox"><img src={preview.images[preview.index].src} alt={preview.images[preview.index].label}/>{preview.images.length>1&&<div className="material-lightbox-controls"><button className="button secondary" onClick={()=>movePreview(-1)}><ChevronLeft size={15}/>上一张</button><span aria-live="polite">{preview.index+1} / {preview.images.length}</span><button className="button secondary" onClick={()=>movePreview(1)}>下一张<ChevronRight size={15}/></button></div>}</div></Modal>}
  </section>;
}
