'use client';
import {useState,type FormEvent} from 'react';
import {ImagePlus,LockKeyhole,Globe,LoaderCircle} from 'lucide-react';
import {api,errorMessage,fileUrl} from '@/lib/client';
import type {Asset,Item,ItemKind,Visibility} from '@/lib/types';
import {Modal} from './modal';

export function Editor({kind,item,onClose,onSaved}:{kind:ItemKind;item?:Item;onClose:()=>void;onSaved:()=>void}){
  const [title,setTitle]=useState(item?.title||'');const [body,setBody]=useState(item?.body||'');const [category,setCategory]=useState(item?.category||(kind==='moment'?'生活':'音乐'));const [tags,setTags]=useState(item?.tags.join('，')||'');const [url,setUrl]=useState(item?.url||'');const [assetId,setAssetId]=useState(item?.assetId||null);const [visibility,setVisibility]=useState<Visibility>(item?.visibility||'private');const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [error,setError]=useState('');
  async function upload(file?:File){if(!file)return;setError('');setUploading(true);try{const form=new FormData();form.append('file',file);form.append('category','记录图片');const data=await api<{file:Asset}>('files',{method:'POST',body:form});if(!data.file.mime.startsWith('image/'))throw new Error('请选择 JPG、PNG、WebP 或 GIF 图片。');setAssetId(data.file.id);}catch(error){setError(errorMessage(error));}finally{setUploading(false);}}
  async function submit(event:FormEvent){event.preventDefault();setError('');setBusy(true);try{if(!title.trim()&&!body.trim()&&!assetId)throw new Error('留几句话或一张照片，再保存吧。');await api(`items${item?'/'+item.id:''}`,{method:item?'PUT':'POST',body:JSON.stringify({kind,title:title.trim()||body.trim().split('\n')[0].slice(0,40)||'今天的小小记录',body,category,tags:tags.split(/[,，]/).map(v=>v.trim()).filter(Boolean),url,assetId,visibility})});onSaved();onClose();}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}
  return <Modal title={item?'编辑这张小卡片':kind==='moment'?'记下一个小瞬间':'收好一份喜欢'} onClose={onClose} wide><form onSubmit={submit} className="form-stack"><label>小标题 <span className="muted">可留空</span><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={160} placeholder={kind==='moment'?'给今天起个小标题':'专辑、舞台或收藏的名字'}/></label><label>{kind==='moment'?'想留下的话':'收藏的理由'}<textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={50000} rows={6} placeholder="几句话也很好。支持简单的 Markdown 排版。"/></label><div className="form-grid"><label>分类{kind==='collection'&&<span className="muted">收藏馆里按它分组</span>}<input value={category} onChange={e=>setCategory(e.target.value)} maxLength={40} list="category-options"/><datalist id="category-options"><option value="生活"/><option value="音乐"/><option value="专辑"/><option value="舞台"/><option value="写真"/><option value="K-pop 小卡"/><option value="动漫"/><option value="电视剧"/><option value="电影"/><option value="综艺"/><option value="游戏"/><option value="其他"/></datalist></label><label>标签<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="K-pop，日常"/></label></div>{kind==='collection'&&<label>收藏链接 <span className="muted">可选</span><input value={url} onChange={e=>setUrl(e.target.value)} type="url" placeholder="https://…" maxLength={2000}/></label>}<div className="image-picker">{assetId&&<div className="image-preview"><img src={fileUrl(assetId,true)} alt="记录配图"/><button type="button" className="text-button" onClick={()=>setAssetId(null)}>移除配图</button></div>}<label className="upload-button"><ImagePlus size={17}/>{uploading?'图片上传中…':'选一张图片'}<input type="file" accept="image/png,image/jpeg,image/gif,image/webp" onChange={e=>void upload(e.target.files?.[0])} disabled={uploading}/></label></div><fieldset className="visibility-picker"><legend>谁可以看见？</legend><label><input type="radio" name="visibility" checked={visibility==='private'} onChange={()=>setVisibility('private')}/><LockKeyhole size={16}/>仅自己</label><label><input type="radio" name="visibility" checked={visibility==='public'} onChange={()=>setVisibility('public')}/><Globe size={16}/>公开给访客</label></fieldset>{visibility==='public'&&<p className="hint">保存为公开后，这段文字和配图都能被访客看见。</p>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={busy||uploading}>{busy&&<LoaderCircle size={16} className="spin"/>}{busy?'保存中…':'保存小卡片'}</button></div></form></Modal>;
}
