'use client';
import {useRef,useState,type FormEvent} from 'react';
import {Settings,LoaderCircle} from 'lucide-react';
import {api,errorMessage,fileUrl} from '@/lib/client';
import type {Asset,Profile} from '@/lib/types';
import {AvatarCrop} from './avatar-crop';
import {AboutFields} from './about-fields';

export function Owner({profile,onSaved}:{profile:Profile;onSaved:(profile:Profile)=>void}){const [draft,setDraft]=useState(profile);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [cropFile,setCropFile]=useState<File|null>(null);const avatarInput=useRef<HTMLInputElement>(null);
  function chooseAvatar(file?:File){if(!file)return;setError('');setNotice('');if(!['image/png','image/jpeg','image/gif','image/webp'].includes(file.type)){setError('请选择 JPG、PNG、WebP 或 GIF 图片。');return;}setCropFile(file);}
  async function avatar(file:File){setError('');setBusy(true);try{const form=new FormData();form.append('file',file);form.append('category','头像');const result=await api<{file:Asset}>('files',{method:'POST',body:form});if(!result.file.mime.startsWith('image/'))throw new Error('图片处理失败，请重新选择照片。');setDraft(current=>({...current,avatarId:result.file.id}));setCropFile(null);setNotice('头像已调整，保存布置后生效。');}finally{setBusy(false);}}
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await api<{profile:Profile}>('profile',{method:'PUT',body:JSON.stringify(draft)});onSaved(result.profile);setNotice('小屋的样子已经更新。');}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}
  return <section className="section-enter"><div className="section-heading"><div><span className="eyebrow">make yourself at home</span><h2>布置我的小屋<span className="heading-dot">.</span></h2><p className="muted">把名字、介绍和喜欢的照片换成你的。</p></div><Settings size={22} className="accent-text"/></div><form className="paper form-stack profile-form" onSubmit={save}><div className="profile-avatar-editor"><button type="button" className="avatar-change" aria-label="更换头像" title="点击更换头像" disabled={busy} onClick={()=>avatarInput.current?.click()}>{draft.avatarId?<img src={fileUrl(draft.avatarId,true)} alt="头像预览"/>:<span className="assistant-mark">m.</span>}</button><input ref={avatarInput} type="file" hidden aria-label="选择头像照片" accept="image/png,image/jpeg,image/gif,image/webp" onChange={e=>{chooseAvatar(e.target.files?.[0]);e.target.value='';}} disabled={busy}/>{draft.avatarId&&<button type="button" className="text-button" onClick={()=>setDraft({...draft,avatarId:null})}>用唱片装饰</button>}</div><p className="hint">保存后，头像和以下介绍会公开展示。</p><label>小屋名称<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required maxLength={50}/></label><label>首页的一句话<input value={draft.subtitle} onChange={e=>setDraft({...draft,subtitle:e.target.value})} maxLength={100}/></label><label>个人介绍<textarea value={draft.bio} onChange={e=>setDraft({...draft,bio:e.target.value})} rows={3} maxLength={300}/></label><AboutFields draft={draft} onChange={setDraft} busy={busy}/><label className="color-field">粉色点缀<input type="color" value={draft.accent} onChange={e=>setDraft({...draft,accent:e.target.value})}/><span className="muted">{draft.accent}</span></label>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}<div className="form-actions"><button className="button primary" disabled={busy}>{busy&&<LoaderCircle size={16} className="spin"/>}{busy?'保存中…':'保存布置'}</button></div></form>{cropFile&&<AvatarCrop file={cropFile} onClose={()=>setCropFile(null)} onConfirm={avatar}/>}</section>;
}
